// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf-67SVEqA8iYzYjW9_Kn_m45b25ANOWg',
    appId: '1:746609234929:web:3d752a6176af35ccb7ea50',
    messagingSenderId: '746609234929',
    projectId: 'twocpro-737b3',
    authDomain: 'twocpro-737b3.firebaseapp.com',
    storageBucket: 'twocpro-737b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtTwX7gTYl9MjjbrIvCyCGiFuamdpXtnk',
    appId: '1:746609234929:android:252524f49ca468f4b7ea50',
    messagingSenderId: '746609234929',
    projectId: 'twocpro-737b3',
    storageBucket: 'twocpro-737b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgTth0pDRr94CwNGfmcMi3ZXKpz1sZfjU',
    appId: '1:746609234929:ios:5dd1a50711ded02bb7ea50',
    messagingSenderId: '746609234929',
    projectId: 'twocpro-737b3',
    storageBucket: 'twocpro-737b3.appspot.com',
    iosBundleId: 'com.example.easytheyka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgTth0pDRr94CwNGfmcMi3ZXKpz1sZfjU',
    appId: '1:746609234929:ios:5dd1a50711ded02bb7ea50',
    messagingSenderId: '746609234929',
    projectId: 'twocpro-737b3',
    storageBucket: 'twocpro-737b3.appspot.com',
    iosBundleId: 'com.example.easytheyka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf-67SVEqA8iYzYjW9_Kn_m45b25ANOWg',
    appId: '1:746609234929:web:5f0c217d0ec783eeb7ea50',
    messagingSenderId: '746609234929',
    projectId: 'twocpro-737b3',
    authDomain: 'twocpro-737b3.firebaseapp.com',
    storageBucket: 'twocpro-737b3.appspot.com',
  );

}